env:
  browser: true
  es2021: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ['./tsconfig.json']
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  comma-dangle:
    - 1
    - only-multiline
  jsx-quotes:
    - error
    - prefer-double
