export const VIEW_BLOG_LIST = 'VIEW_BLOG_LIST'
export const VIEW_BLOG = 'VIEW_BLOG'
export const CREATE_BLOG = 'CREATE_BLOG'
export const DELETE_BLOG = 'DELETE_BLOG'
export const UPDATE_BLOG = 'UPDATE_BLOG'
